config/routes.rb
Rails.application.routes.draw do
  resources :establishments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/establishment.rb
class Establishment < ApplicationRecord

  validates :code, presence: { message: "Merci d'ajouter un code." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
  before_action :set_establishment, only: %i[ show edit update destroy ]

  # GET /establishments or /establishments.json
  def index
    @establishments = Establishment.all
  end

  # GET /establishments/1 or /establishments/1.json
  def show
  end

  # GET /establishments/new
  def new
    @establishment = Establishment.new
  end

  # GET /establishments/1/edit
  def edit
  end

  # POST /establishments or /establishments.json
  def create
    @establishment = Establishment.new(establishment_params)


    if @establishment.save
      redirect_to establishments_url, notice: "Etablissement créé."
    else
      broadcast_errors @establishment, establishment_params
    end
  end

  # PATCH/PUT /establishments/1 or /establishments/1.json
  def update

      if @establishment.update(establishment_params)
        redirect_to @establishment, notice: "Etablissement mis à jour."
      else
        broadcast_errors @establishment, establishment_params
      end
  end

  # DELETE /establishments/1 or /establishments/1.json
  def destroy
    @establishment.destroy
    redirect_to establishments_url, notice: "Etablissement effacé."

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_establishment
      @establishment = Establishment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def establishment_params
      params.require(:establishment).permit(:code, :title, :address, :npa, :locality, :email, :phone1, :phone2, :fax)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/establishments_helper.rb
module EstablishmentsHelper
end

app/views/establishments/_form.html.erb
<%= form_with(model: establishment, local: false) do |form| %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
    <%= form.error_for :code %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.error_for :title %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :npa %>
    <%= form.text_field :npa %>
  </div>

  <div class="field">
    <%= form.label :locality %>
    <%= form.text_field :locality %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone1 %>
    <%= form.text_field :phone1 %>
  </div>

  <div class="field">
    <%= form.label :phone2 %>
    <%= form.text_field :phone2 %>
  </div>

  <div class="field">
    <%= form.label :fax %>
    <%= form.text_field :fax %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/establishments/edit.html.erb
<h1>Editing Establishment</h1>

<%= render 'form', establishment: @establishment %>

<%= link_to 'Show', @establishment %> |
<%= link_to 'Back', establishments_path %>

app/views/establishments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Establishments</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Title</th>
      <th>Address</th>
      <th>Npa</th>
      <th>Locality</th>
      <th>Email</th>
      <th>Phone1</th>
      <th>Phone2</th>
      <th>Fax</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @establishments.each do |establishment| %>
      <tr>
        <td><%= establishment.code %></td>
        <td><%= establishment.title %></td>
        <td><%= establishment.address %></td>
        <td><%= establishment.npa %></td>
        <td><%= establishment.locality %></td>
        <td><%= establishment.email %></td>
        <td><%= establishment.phone1 %></td>
        <td><%= establishment.phone2 %></td>
        <td><%= establishment.fax %></td>
        <td><%= link_to 'Show', establishment %></td>
        <td><%= link_to 'Edit', edit_establishment_path(establishment) %></td>
        <td><%= link_to 'Destroy', establishment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Establishment', new_establishment_path %>

app/views/establishments/new.html.erb
<h1>Nouvelle établissement</h1>

<%= render 'form', establishment: @establishment %>

<%= link_to 'Back', establishments_path %>

app/views/establishments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @establishment.code %>
</p>

<p>
  <strong>Title:</strong>
  <%= @establishment.title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @establishment.address %>
</p>

<p>
  <strong>Npa:</strong>
  <%= @establishment.npa %>
</p>

<p>
  <strong>Locality:</strong>
  <%= @establishment.locality %>
</p>

<p>
  <strong>Email:</strong>
  <%= @establishment.email %>
</p>

<p>
  <strong>Phone1:</strong>
  <%= @establishment.phone1 %>
</p>

<p>
  <strong>Phone2:</strong>
  <%= @establishment.phone2 %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @establishment.fax %>
</p>

<%= link_to 'Edit', edit_establishment_path(@establishment) %> |
<%= link_to 'Back', establishments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>Profa</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>